# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField()),
                ('message', models.CharField(max_length=300)),
                ('finish', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('start_at',),
            },
        ),
    ]
